# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e060d39b1c7db0f8bda757c43f19eb709d8365277af3803d1763f37f1a30a34d7a99697bef6f616d58f92af7e4696eed3716acb7440fa480d771e6077f5a207

test:
  secret_key_base: d1b8040d8b579cc6ba7b98935357e186f05042e0719d0332640f8188ce343c6e2a1899664844e6bfe2e66da27777332dab4b0afade2d63102fef42da576a0270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
